Markup/#17
CBNU-CMI/cbnu_ulrim pull request #18
Opened 2020-11-26 16:56 UTC by nohgijin

![image](https://user-images.githubusercontent.com/38103082/100376702-561b9880-3053-11eb-9a01-ceccf74a37bf.png)
- 로그인 페이지 마크업 작업을 했습니다.
- input 창, 선, box 는 element로 만들었습니다. 
- ❓margin을 주어 스타일을 조절해야 하는 경우 

```
function Box({
  margin,
  ...
}) {
  return (
    <div className=...style={{ marginBottom: margin }}>
    </div>
  );
}
```
이런식으로 했는데 맞는지는 잘 모르겠습니다 ㅎㅎ😂

2020-11-27 13:18 UTC, danivelop requested changes

2020-11-27 13:18 UTC, danivelop commented on src/components/Login/Login.tsx
> +  );
자바스크립트에서 form관리하는 방법에는 직접 form태그써서 관리하는 방법도 있지만 생산성이 떨어지고 일반적으로 라이브러리를 사용하는데 그중 제가 아는것중 유명한게 redux-form과 formik이 있습니다. redux-form은 설정이 까다로운 부분이 있고 formik는 사용법도 간단하고 코드가 깔끔해서 한번 이기회에 form라이브러리 사용해보시면 어떨까요? 현업에서도 form은 거의 라이브러리를 사용합니다.

2020-11-27 13:18 UTC, danivelop commented on src/elements/Box/Box.tsx
> +    <div className={cx('button', type, size)} style={{ marginBottom: margin }}>
margin을 props로 받아서 조절하기 위해 인라인스타일을 넣은것 같은데 물론 필요하다면 넣어야하겠지만 인라인 스타일은 규모가 커질수록 관리하기 까다로운 부분이 있는거 같아요

위의 경우처럼 element같은 느낌의 컴포넌트는 저렇게 number값을 props로 받아 적용시키는 경우가 많아서 elements폴더에 만들어질 컴포넌트들은 styled-component를 사용해보면 좋을것 같습니다. 혹시 styled-component를 사용해본적 없으면 이번주 스터디때  한번 살펴보는것도 괜찮을것 같습니다

2020-11-27 13:18 UTC, danivelop commented on src/elements/Box/Box.tsx
> +
interface BoxProps {
  margin?: number
  text?: string
  moveText?: string
  link?: string
  type?: BoxType
  size:?: BoxSize
}
으로 타입정의 해주면 좋을것 같습니다
BoxType와 BoxSize는 enum타입으로 정의해주면 될것 같습니다. 이것도 혹시 익숙하지 않으면 이번주 스터디때 같이 봐도 괜찮을것 같습니다

2020-11-27 13:18 UTC, danivelop commented on src/elements/Button/Button.tsx
> +    <div className={cx('button', type, size)} onClick={onClick}>
onClick속성도 현재는 Button컴포넌트에 onClick속성만 전달해줄수 있는데 Button컴포넌트의 경우 실제로 onMouseDown등의 다른 이벤트도 전달하는 경우가 많아 그부분까지 고려하면 좋을것 같습니다! 좋은 방법이 안떠오르시면 남겨뒀다 이번주 스터디때 봐도 좋을것같습니다

2020-11-27 13:18 UTC, danivelop commented on src/pages/PetitionPage/PetitionPage.tsx
> +  const titleRef = useRef<any>(null);
이건 혹시 어떤 문제때문에 다시 any로 바꾸신건가요? 아니면 카톡으로 말씀해주셨던 커밋 꼬이신것 때문일까요?

2020-11-27 13:18 UTC, danivelop commented on src/pages/SignupPage/SignupPage.tsx
> +      <Navigation title="로그인" className="" />
이부분도 중첩라우팅 방식으로 하면 따로 Navigation을 써주지 않아도 될것 같은데 요것도 이번주 스터디때 같이 보도록 합시다!

2020-11-28 07:17 UTC, nohgijin commented on src/pages/PetitionPage/PetitionPage.tsx
> +  const titleRef = useRef<any>(null);
HTMLHeadingElement로 해보니까 오류가 나서 우선 any로 바꿔놨어요!

2020-11-28 07:36 UTC, nohgijin commented on src/components/Login/Login.tsx
> +  );
formik 한번 써보겠습니다!!

2020-11-28 07:37 UTC, nohgijin commented on src/pages/SignupPage/SignupPage.tsx
> +      <Navigation title="로그인" className="" />
넵!!🙃🙂

2020-11-28 13:10 UTC, nohgijin commented on src/elements/Box/Box.tsx
> +    <div className={cx('button', type, size)} style={{ marginBottom: margin }}>
아하.. 그럼 이경우에는 element 파일 내에서 styled-component를 사용하면 되는거군욤.!

2020-11-28 14:02 UTC, jaryapp approved these changes

2020-11-28 17:05 UTC, nohgijin commented on src/elements/Box/Box.tsx
> +
enum을 쓰는 이유가 매직넘버를 지양하려고 쓰는 건가요?

2020-11-28 17:08 UTC, nohgijin commented on src/elements/Button/Button.tsx
> +    <div className={cx('button', type, size)} onClick={onClick}>
이건 고민해봤는데 잘 모르겠네요ㅠ.ㅠ

2020-11-29 14:20 UTC, danivelop approved these changes

2020-11-29 14:26 UTC, merged